# Generated by Django 4.2.16 on 2024-11-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_order_payment_remove_order_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
