# Generated by Django 4.2.16 on 2024-11-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_payment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='show',
        ),
    ]
