from .views import *
from django.urls import path

urlpatterns = [
    path("", FilmListView.as_view(), name = "home"),
    path("user_list/", UserListView.as_view(), name = "user_list"),
    path("user_detail/<int:pk>/", UserDetailView.as_view(), name = "user_detail"),
    path("user_create/", UserCreateView.as_view(), name = "user_create"),
    path("user_update/<int:pk>/", UserUpdateView.as_view(), name = "user_update"),
    path("user_delete/<int:pk>/", UserDeleteView.as_view(), name = "user_delete"),
    path("janre_list/", JanreListView.as_view(), name = "janre_list"),
    path("janre_detail/<int:pk>/", JanreDetailView.as_view(), name = "janre_detail"),
    path("janre_create/", JanreCreateView.as_view(), name = "janre_create"),
    path("janre_update/<int:pk>/", JanreUpdateView.as_view(), name = "janre_update"),
    path("janre_delete/<int:pk>/", JanreDeleteView.as_view(), name = "janre_delete"),
    path("teatr_list/", TeatrListView.as_view(), name = "teatr_list"),
    path("teatr_detail/<int:pk>/", TeatrDetailView.as_view(), name = "teatr_detail"),
    path("teatr_create/", TeatrCreateView.as_view(), name = "teatr_create"),
    path("teatr_update/<int:pk>/", TeatrUpdateView.as_view(), name = "teatr_update"),
    path("teatr_delete/<int:pk>/", TeatrDeleteView.as_view(), name = "teatr_delete"),
    path("film_list/", FilmListView.as_view(), name = "film_list"),
    path("film_detail/<int:pk>/", FilmDetailView.as_view(), name = "film_detail"),
    path("film_create/", FilmCreateView.as_view(), name = "film_create"),
    path("film_update/<int:pk>/", FilmUpdateView.as_view(), name = "film_update"),
    path("film_delete/<int:pk>/", FilmDeleteView.as_view(), name = "film_delete"),
    path("show_list/", ShowListView.as_view(), name = "show_list"),
    path("show_detail/<int:pk>/", ShowDetailView.as_view(), name = "show_detail"),
    path("show_create/", ShowCreateView.as_view(), name = "show_create"),
    path("show_update/<int:pk>/", ShowUpdateView.as_view(), name = "show_update"),
    path("show_delete/<int:pk>/", ShowDeleteView.as_view(), name = "show_delete"),
    path("order_list/", OrderListView.as_view(), name = "order_list"),
    path("order_detail/<int:pk>/", OrderDetailView.as_view(), name = "order_detail"),
    path("order_create/", OrderCreateView.as_view(), name = "order_create"),
    path("order_update/<int:pk>/", OrderUpdateView.as_view(), name = "order_update"),
    path("order_delete/<int:pk>/", OrderDeleteView.as_view(), name = "order_delete"),
    path("trailer/<int:pk>/", TrailerListView.as_view(), name = "trailer"),
    path("payment/", PaymentListView.as_view(), name = "payment"),
]
